### ISSUE TITLE
Documentation/Steps to run RBM requires review

### ISSUE THREAD

**Issue by YifanCheng** [UW-Hydro/RBM#20]
Reviews are appreciated through RBM website - Steps to run RBM

URL: http://rbm.readthedocs.io/en/latest/Documentation/run_RBM/

Mainly check whether it makes sense or readable. Please offer your suggestions!

**Comment by yixinmao** [comment]
`Steps to run RBM`:
- First sentence: "The following describes ..."
** In section `1. Download Source Code & Example Datasets`:
- For the `DESCRIPTION` file - what does it mean for the line "The file:"?
- I like that you have a table describing subdirectories. But the files I downloaded following your links don't seem to match your folder descriptions?
- Remove all the "- contains" at the beginning of each description in the table
** In section `2. Create the RBM Executable`:
- When it says `../src`, which directory are you assuming the user is in?
** In section `3. Run the Model`:
- I'd change the step 1 title to something like: Generate flow and meteorology files using VIC. Also, avoid using `I` in the text. I also find step 1 a bit redundant - e.g., you described twice that there are two global parameter files in the directory.
- Maybe use `Note:` instead of `PS`?
- In step 2, the link to `VIC model` doesn't seem correct; and it's still not clear how to create the flow direction file (is it something that you just simply need to prepare yourself, or is our group providing any tools?)
- `All the grid cells surrounding the basin of interest must contain a negative one (-1) for purposes of determining the headwaters segments.` I'm not sure what this sentence mean.
- `but there must only be one single outlet`
- `the Columbia River system **can** be modeled in its entirety`
- In step 3 - where's figure 1? Also some descriptions are missing in the table (can still write description to clarify for things that might seem obvious)
- In step 4 - `using the control file,(Salmon_0.5.Control) ` -  seems to have some punctuation problem (similar problem later in this section
- `the ordered input file`? What does it mean?
- Where's Appendix A?
- Title of step 5: input files (plural)
- `Build the forcing function files for flow and heat budget using rout.` What's "rout"?
- `Create control file, salmon.inp_DA, to run the modified Lohmann routing model using the file, Rout.Cells.init, the first time and the file, Rout.Cells, if the routing model, rout is run again for the same set of unit hydrographs. ` There are too many commas in this sentence. Kind of hard to understand.
- `The input file (in this example, salmon.inp_DA) is similar to that described on the VIC model Web site with the exception of the addition the Leopold parameters. ` - I guess you mean the Lohmann routing model page - give the link.

**Comment by yixinmao** [comment]
`Tutorial`:
- `Model development and implementation for the large-scale hydrologic model, VIC are described in detail on the Web site of the University of Washington Department of Civil and Environmental Engineering's UW Hydro|Computational Hydrology group` - don't need the comma; also, "website"
** In 1 overview **:
- `As presently configured, the VIC-RBM model system simulates daily-averaged stream temperatures, only.`  - is it true? Also, don't need the comma
** In 2 model input **:
- `VIC implements algorithms which are able to generate a full set of meteorological variables (see model output section for a list of meteorological variables) at daily or sub- daily time steps. These variables can also be directly given as input.` - this is kind of confusing. Better to say something like - VIC includes a meteorological data disaggregator that calculates subdaily meteorological variables required by VIC from the minimum forcing variables. I guess you can also simply refer to the VIC documentation.
- Lohmann routing input is more than flow direction and UH (e.g., runoff data, flow velocity and diffusivity, etc.). Maybe simply refer to the routing model documentation?
- The first bullet point under `3)Input for the RBM stream temperature model` seems to not be a "model input"?
- `charaacteristics` - typo
** Model output **:
- Hmm not sure if you need to list out the `Grid-cell-based meteorological data` section - I feel like this is more like input?
- `calculated by the routing model, daily or subdaily time step.` - actually can Lohmann routing model simulate subdaily flow?
